Implementation
khadasevich/automation_training_final_task pull request #1
Opened 2020-11-17 17:49 UTC by khadasevich

2020-11-25 13:53 UTC, artemmoroz requested changes

2020-11-25 13:53 UTC, artemmoroz commented on pom.xml
> +            <groupId>org.seleniumhq.selenium</groupId>
instead of this u can use lib https://github.com/bonigarcia/webdrivermanager that will handle all stuff for loading drivers and etc

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/listeners/TestListener.java
> +public class TestListener extends BaseTest implements ITestListener {
very bad idea to extend listener from class, i understand that u do that to get access to driver, thibk about another solution

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/listeners/TestListener.java
> +public class TestListener extends BaseTest implements ITestListener {
amm, seems that im wrong, and did not understand what for u extentlistener

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/listeners/TestListener.java
> +        DriverManager driverManager = ((BaseTest) testClass).getDriver();
not very good idea

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/pages/GmailMainPage.java
> +    @FindBy (xpath = "//div[contains(text(), 'Compose')]")
is that the only locator?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/pages/GmailMainPage.java
> +    @FindBy (xpath = "//div[@class='iH bzn']//div[@class='G-tF']//div[2][@class='G-Ni G-aE J-J5-Ji']")
sure?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/pages/GmailMainPage.java
> +        action.moveToElement(firstElementInbox).click().build().perform();
what for such complex solution?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/pages/GmailMainPage.java
> +    public WebElement getEmailTextElement() {
u can use lombok lib and not write this getts/setters

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/pages/SelectAccountPage.java
> +    @FindBy (xpath = "//*[@id='yDmH0d']//descendant::span[contains(text(), 'Удалить')][4]")
sure? id - seems to be dynamic, and text. -ydalit?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/pages/SelectAccountPage.java
> +    @FindBy (xpath = "//div[@id='initialView']")
why not yo use id by, or #css instead of xpath in this case and some others above?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/BaseTest.java
> +    public DriverManager getDriver() {
not a very good name for a method that returns DriverManager

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/BaseTest.java
> +    public void goThroughLogin(String username, String password) {
seems that these methods should be protected or so

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/BaseTest.java
> +    public void goThroughLogin(String username, String password) {
and, why not implement the in proper pages?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/EmailSendingTests.java
> +        String usernameOne = "seleniumtests10";
what about external parametrization for this test, by parameters/dataproviders/some custom solution?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/EmailSendingTests.java
> +        String expectedResult = TestTools.fakeMessageGenerator();
bad name `expectedResult`

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/EmailSendingTests.java
> +        logoutRemoveAccount();
what will happen with logout, if the assertion fails?

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/InboxTests.java
> +        String expectedResult = TestTools.fakeMessageGenerator();
the same, as for prev test

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/LoginTests.java
> +        String filename = "C:\\Testing\\AutomationTrainingFinalTask\\src\\test\\resources\\test_data";
no absolute paths should be in code!

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tests/LoginTests.java
> +        Gson gson = new Gson();
i think gson has a super feature to read json straight from fileName or File object, withgout JsonArray and so on

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tools/TestTools.java
> +public class TestTools {
incorrect names for this methods

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/tools/TestTools.java
> +public class TestTools {
and think about aggregation/facade this methods

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/webdriver/DriverFactory.java
> +        String hubUrl = "http://192.168.0.2:4444/wd/hub";
config

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/webdriver/DriverFactory.java
> +    public WebDriver getDriver() {
think about an option, to create one method getWebDriver that will return(create) proper driver according to props,

2020-11-25 13:53 UTC, artemmoroz commented on src/test/java/webdriver/DriverManager.java
> +    public void waitUntilItemWillBeShown (WebElement element) {
is it a really good place for such kind of methods?

2020-12-02 05:47 UTC, khadasevich commented on pom.xml
> +            <groupId>org.seleniumhq.selenium</groupId>
Manager added

2020-12-02 05:48 UTC, khadasevich commented on src/test/java/listeners/TestListener.java
> +        DriverManager driverManager = ((BaseTest) testClass).getDriver();
Updated driver manager to return driver

2020-12-02 05:48 UTC, khadasevich commented on src/test/java/pages/GmailMainPage.java
> +    @FindBy (xpath = "//div[contains(text(), 'Compose')]")
Changed

2020-12-02 05:49 UTC, khadasevich commented on src/test/java/pages/GmailMainPage.java
> +    @FindBy (xpath = "//div[@class='iH bzn']//div[@class='G-tF']//div[2][@class='G-Ni G-aE J-J5-Ji']")
Slightly updated, but I didn't find the to fully avoid such classes

2020-12-02 05:49 UTC, khadasevich commented on src/test/java/tests/LoginTests.java
> +        Gson gson = new Gson();
Updated

2020-12-02 05:49 UTC, khadasevich commented on src/test/java/tools/TestTools.java
> +public class TestTools {
Separated on different tools

2020-12-02 05:50 UTC, khadasevich commented on src/test/java/pages/GmailMainPage.java
> +        action.moveToElement(firstElementInbox).click().build().perform();
On first try I didn't manage to open items without hovering, now seems like it works without it, updated

2020-12-02 05:51 UTC, khadasevich commented on src/test/java/pages/GmailMainPage.java
> +    public WebElement getEmailTextElement() {
Lombok lib added

2020-12-02 05:51 UTC, khadasevich commented on src/test/java/pages/SelectAccountPage.java
> +    @FindBy (xpath = "//*[@id='yDmH0d']//descendant::span[contains(text(), 'Удалить')][4]")
Updated

2020-12-02 05:51 UTC, khadasevich commented on src/test/java/pages/SelectAccountPage.java
> +    @FindBy (xpath = "//div[@id='initialView']")
Updated

2020-12-02 05:52 UTC, khadasevich commented on src/test/java/tests/BaseTest.java
> +    public DriverManager getDriver() {
Method removed at all

2020-12-02 05:53 UTC, khadasevich commented on src/test/java/tests/BaseTest.java
> +    public void goThroughLogin(String username, String password) {
These methods are results of decomposition of common steps into one place to don't repeat code, login moved to the proper page but other methods require items from different places. Probably it'd be better to create separate class for these methods?

2020-12-02 05:54 UTC, khadasevich commented on src/test/java/tests/EmailSendingTests.java
> +        String usernameOne = "seleniumtests10";
Parameters added

2020-12-02 05:54 UTC, khadasevich commented on src/test/java/tests/EmailSendingTests.java
> +        String expectedResult = TestTools.fakeMessageGenerator();
Updated

2020-12-02 05:54 UTC, khadasevich commented on src/test/java/tests/EmailSendingTests.java
> +        logoutRemoveAccount();
Moved under aftermethod annotations

2020-12-02 05:54 UTC, khadasevich commented on src/test/java/tests/InboxTests.java
> +        String expectedResult = TestTools.fakeMessageGenerator();
Moved under aftermethod annotations

2020-12-02 05:55 UTC, khadasevich commented on src/test/java/tests/LoginTests.java
> +        String filename = "C:\\Testing\\AutomationTrainingFinalTask\\src\\test\\resources\\test_data";
Updated

2020-12-02 05:55 UTC, khadasevich commented on src/test/java/webdriver/DriverFactory.java
> +        String hubUrl = "http://192.168.0.2:4444/wd/hub";
Moved to config

2020-12-02 05:56 UTC, khadasevich commented on src/test/java/webdriver/DriverFactory.java
> +    public WebDriver getDriver() {
Method for initiation driver added, now getDriver returns proper driver

2020-12-02 05:56 UTC, khadasevich commented on src/test/java/webdriver/DriverManager.java
> +    public void waitUntilItemWillBeShown (WebElement element) {
Waits moved to separate class

2020-12-09 10:40 UTC, artemmoroz requested changes

2021-01-26 17:39 UTC, artemmoroz approved these changes
there are some places where you code "smells" a little, but in general, i think it ok

2021-01-26 17:40 UTC, merged